Hussmann Prototypes/Hussmann Release/Compressor/Hussmann/Controllers/CondenserController.cs
using Hussmann.Attribute;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Hussmann.Common.Enumeration;
using Hussmann.Models.Condenser.Add;
using CondenserDataModel;
using Hussmann.Common.Helper;
using System.Data;
using Newtonsoft.Json;
using System.Data.SqlClient;
using Hussmann.Models.Condenser.RefrigerantType;
using System.Web.Script.Serialization;
using NPOI.SS.UserModel;
using NPOI.HSSF.UserModel;
using System.IO;

namespace Hussmann.Controllers
{
    public class CondenserController : BaseController
    {
        private RulestreamCondenserDBEntities CondenserDBContext = new RulestreamCondenserDBEntities();
        public int CurrentCondenserID;
        public bool IsDraftMode;
        public string userType;
        public string userName;
        public static string mode;
        [HttpGet]
        public ActionResult SearchCondenser(string modelNumber, int? condenserBrandId, int? condenserFamilyId, int? statusId, bool? pinned = true)
        {
            Logger.PrintInfo("Action:Search ~~~~~~ Search Screen");
            userType = Authorization.GetUserType(HttpContext.ApplicationInstance.Context);
            userName = User.Identity.Name.Split('\\')[1];
            ViewBag.ModelNumberParm = modelNumber;
            ViewBag.BrandID = condenserBrandId;
            ViewBag.FamilyId = condenserFamilyId;
            ViewBag.StatusId = statusId;
            ViewBag.PinnedTab = pinned;

            ViewBag.PinnedTab = pinned;

            var CondenserBrand = CondenserDBContext.CondenserBrand_lkp
            .Select(s => new
            {
                BrandID = s.BrandID,
                CondenserBrandName = s.CondenserBrandName + " " + s.CondenserSubBrandName
            }).ToList();

            var ModelSuffixes = CondenserDBContext.ModelSuffixes
            .Select(s => new
            {
                ModelSuffixID = s.ModelSuffixID,
                ModelSuffix = s.ModelSuffix1
            }).ToList();

            ViewBag.BrandList = new SelectList(CondenserBrand, "BrandID", "CondenserBrandName", condenserBrandId);
            ViewBag.FamilyList = new SelectList(CondenserDBContext.CondenserFamilies, "CondenserFamilyID", "CondenserFamilyName", condenserFamilyId);
            ViewBag.StatusList = new SelectList(CondenserDBContext.States, "StateID", "Description", statusId);

            if (userType == Convert.ToString(enUserType.Reader))
            {
                ViewBag.EditOrView = "View";
                ViewBag.IconImage = "fa fa-eye";
            }
            else
            {
                ViewBag.EditOrView = "Edit";
                ViewBag.IconImage = "fa fa-pencil";
            }
            ViewBag.userType = userType;
            ViewBag.userName = userName;

            return View();
        }

        public ActionResult GetCondenserData(string modelNumber, int? condenserBrandId, int? condenserFamilyId, int? StatusId, string Page)
        {
            JsonResult result = new JsonResult();

            string search = Request.Form.GetValues("search[value]")[0];
            string draw = Request.Form.GetValues("draw")[0];
            string order = Request.Form.GetValues("order[0][column]")[0];
            string orderDir = Request.Form.GetValues("order[0][dir]")[0];
            int startRec = Convert.ToInt32(Request.Form.GetValues("start")[0]);
            int pageSize = Convert.ToInt32(Request.Form.GetValues("length")[0]);

            //Initialize User Name And UserType 
            userType = Authorization.GetUserType(HttpContext.ApplicationInstance.Context);
            userName = User.Identity.Name.Split('\\')[1];


            if (modelNumber == "null" || modelNumber == "Null")
            {
                modelNumber = null;
            }

            if (orderDir == "desc")
            {
                orderDir = "Descending";
            }
            else if (orderDir == "asc")
            {
                orderDir = "Ascending";
            }
            //Total record count.
            int? totalRecords = CondenserDBContext.spGetRowsCountForSearch(modelNumber, condenserBrandId, condenserFamilyId, StatusId, userName, userType).SingleOrDefault(); ;
            int? recFilter = totalRecords;
            List<spSearchCondenser_Result> searchResult = new List<spSearchCondenser_Result>();

            //Search
            if (!string.IsNullOrEmpty(search) &&
                   !string.IsNullOrWhiteSpace(search))
            {
                // Apply search
                string sortExpression = GetSortExpression(order);
                searchResult = CondenserDBContext.spSearchCondenser(modelNumber, condenserBrandId, condenserFamilyId, StatusId, userName, userType, 0, totalRecords, sortExpression, orderDir).ToList();
                searchResult = searchResult.Where(p => p.ModelNumber.ToString().ToLower().Contains(search.ToLower()) ||
                    p.CondenserBrandName.ToLower().Contains(search.ToLower()) ||
                    p.CondenserFamilyName.ToLower().Contains(search.ToLower()) ||
                    p.ModelSuffixID.ToString().ToLower().Contains(search.ToLower()) ||
                    p.StateDescription.ToLower().Contains(search.ToLower()) ||
                    p.Version.ToString().ToLower().Contains(search.ToLower()) ||
                    p.LastModifiedOn.ToString().ToLower().Contains(search.ToLower()) ||
                    p.ActionBy.ToLower().Contains(search.ToLower())).ToList();
                recFilter = searchResult.Count;
                searchResult = searchResult.Skip(startRec).Take(pageSize).ToList();
            }
            else
            {
                string sortExpression = GetSortExpression(order);
                searchResult = CondenserDBContext.spSearchCondenser(modelNumber, condenserBrandId, condenserFamilyId, StatusId, userName, userType, startRec + 1, startRec + pageSize, sortExpression, orderDir).ToList();

            }

            //Initialize Json
            result = this.Json(new
            {
                draw = Convert.ToInt32(draw),
                recordsTotal = totalRecords,
                recordsFiltered = recFilter,
                data = searchResult
            }, JsonRequestBehavior.AllowGet);
            ViewBag.Page = 1;
            return result;
        }

        private string GetSortExpression(string order)
        {
            try
            {
                switch (order)
                {
                    case "0":
                        // Setting.   
                        return Convert.ToString(enCondenserSortExpression.ModelNumber);
                    case "1":
                        // Setting.  
                        return Convert.ToString(enCondenserSortExpression.CondenserBrandName);
                    case "2":
                        // Setting. 
                        return Convert.ToString(enCondenserSortExpression.CondenserFamilyName);
                    case "3":
                        // Setting.   
                        return Convert.ToString(enCondenserSortExpression.ModelSuffixID);
                    case "4":
                        // Setting.  
                        return Convert.ToString(enCondenserSortExpression.StateDescription);
                    case "5":
                        // Setting. 
                        return Convert.ToString(enCondenserSortExpression.Version);
                    case "6":
                        // Setting. 
                        return Convert.ToString(enCondenserSortExpression.LastModifiedOn);
                    case "7":
                        // Setting. 
                        return Convert.ToString(enCondenserSortExpression.ActionBy);

                    default:
                        // Setting.  
                        return Convert.ToString(enCondenserSortExpression.LastModifiedOn);
                }
            }
            catch (Exception ex)
            {
                Logger.PrintError(ex);
            }
            return Convert.ToString(enCondenserSortExpression.LastModifiedOn);
        }
        // GET: UnitCondenser
        public ActionResult Index()
        {
            return View();
        }

        // GET: Add or Edit Refrigerant Type
        public ActionResult AddRefrigerantType(int? ModelID)
        {
            if (ModelID != null)
            {
                var RefrigerantTypeDB = CondenserDBContext.RefrigerantType.Where(m => m.RefrigerantType_ID == ModelID).Select(x => new { x.RefrigerantType_ID, x.RefrigerantType1, x.RefrigerantDescr, x.Active, x.Obsolete }).SingleOrDefault();
                RefrigerantTypeViewModel RefrigerantType = new RefrigerantTypeViewModel()
                {
                    RefrigerantType_ID = RefrigerantTypeDB.RefrigerantType_ID,
                    RefrigerantType1 = RefrigerantTypeDB.RefrigerantType1,
                    RefrigerantDescr = RefrigerantTypeDB.RefrigerantDescr,
                    Active = RefrigerantTypeDB.Active,
                    Obsolete = RefrigerantTypeDB.Obsolete
                };

                return PartialView("EditRefrigerantType", RefrigerantType);
            }
            List<RefrigerantTypeViewModel> RefrigerantTypes = new List<RefrigerantTypeViewModel>();
            foreach (var item in CondenserDBContext.RefrigerantType.Select(x => new { x.RefrigerantType_ID, x.RefrigerantType1, x.RefrigerantDescr, x.Active, x.Obsolete }).ToList())
            {
                RefrigerantTypeViewModel RefrigerantType = new RefrigerantTypeViewModel()
                {
                    RefrigerantType_ID = item.RefrigerantType_ID,
                    RefrigerantType1 = item.RefrigerantType1,
                    RefrigerantDescr = item.RefrigerantDescr,
                    Active = item.Active,
                    Obsolete = item.Obsolete
                };
                RefrigerantTypes.Add(RefrigerantType);
            }

Hussmann Prototypes/Hussmann Release/Compressor/Hussmann/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hussmann.Attribute;
using Hussmann.Common;
using Hussmann.Common.Helper;
using Hussmann.Models;
using UnitCoolerDataModel;

namespace Hussmann.Controllers
{
    public class HomeController : BaseController
    {
        private RulestreamCoilDBEntities UnitCoolerDBContext = new RulestreamCoilDBEntities();
        public string userType;
        public string userName ;

        //[OutputCache(NoStore = true, Location = System.Web.UI.OutputCacheLocation.Client, Duration = 0)]
        public ActionResult Index()
        {

            //Logger.PrintInfo("Action:Index ~~~~~~ DashBoard");

            // Setting logged in user name
            userName = User.Identity.Name.Split('\\')[1];

            
            userType = Authorization.GetUserType(HttpContext.ApplicationInstance.Context);

            // Creating object to send all data to View (News Feed, Saved Records, Submitted Records, Rejected Records)
            DashboardViewModel dashboardViewModel = new DashboardViewModel();

            // Separate object For calling methods which returns combined data of each database
            DashboardNewsFeed dashboardNewsFeed = new DashboardNewsFeed();
            DashboardSavedRecords dashboardSavedRecords = new DashboardSavedRecords();
            DashboardSubmittedRecords dashboardSubmittedRecords = new DashboardSubmittedRecords();
            DashboardRejectedRecords dashboardRejectedRecords = new DashboardRejectedRecords();


            // Coping data for sending to View
            dashboardViewModel.CombinedNewsFeed = dashboardNewsFeed.GetCombinedListofDashboardNewsFeed(userType, userName);
            dashboardViewModel.CombinedSavedRecords = dashboardSavedRecords.GetCombinedListofDashboardSavedRecords(userType, userName);
            dashboardViewModel.CombinedSubmittedRecords = dashboardSubmittedRecords.GetCombinedListofDashboardSumittedRecords(userType, userName);
            dashboardViewModel.CombinedRejectedRecords = dashboardRejectedRecords.GetCombinedListofDashboardRejectedRecords(userType, userName);

            return View(dashboardViewModel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Hussmann Prototypes/Hussmann Release/Compressor/Hussmann/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Hussmann Prototypes/Hussmann Release/Compressor/Hussmann/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hussmann Prototypes/Hussmann Release/Compressor/Hussmann/Views/Home/Index.cshtml
@using Hussmann.Common.Helper
@using Hussmann.Common.Enumeration
@{
    ViewBag.Title = "Dashboard";

}

<div id="content" class="content">
    <!-- begin page-header -->
    <h1 class="page-header">Dashboard</h1>
    <!-- end page-header -->
    <!-- begin row -->
    <div class="row">
        <!-- Updates col-8 -->
        <div class="col-md-8">
            <!-- begin panel -->
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title"><b>News Feed</b></h4>
                </div>


                <div  class="panel-body">
                    <div class="height-md" data-scrollbar="true">
                        <ul class="media-list media-list-with-divider media-messaging">

                            @foreach (var item in Model.CombinedNewsFeed)
                            {
                                //if (@item.StateID == 5 || @item.StateID == 4 || @item.StateID == 1)
                                //{
                                    <li class="media media-sm">
                                        <img src="@DashboardHelper.GetImageForChillerItem(@item.ChillerType)" alt="" class="media-object rounded-corner pull-left dropdown-toggle f-s-14" />
                                        <a href="javascript:;" class="pull-left dropdown-toggle f-s-14 relative-icon">
                                            <span class="@DashboardHelper.GetIconSpanClass(@item.StateID)"><i class="@DashboardHelper.GetIconImageClass(@item.StateID)"></i></span>
                                        </a>
                                        <div class="media-body">
                                            <p class="pull-right m-b-0">
                                                <span class="small block text-right m-b-10">@item.LastModifiedOn</span>
                                                @if (@item.StateID != 5)
                                                {
                                                    if (@item.ChillerType == enChillerType.UnitCooler.ToString())
                                                    {
                                                        <a href="@Url.Action("EditUnitCooler", "UnitCooler",new {ModelID = @item.ModelID, RedirectTo = Convert.ToString(enAction.Index), queryStringParameters = "" })" class="btn btn-primary btn-sm m-l-5 pull-right m-b-5">View</a>
                                                    }
                                                    else if (@item.ChillerType == enChillerType.Condenser.ToString())
                                                    {
                                                        <a href="@Url.Action("EditCondenser", "Condenser",new {ModelID = @item.ModelID, RedirectTo = Convert.ToString(enAction.Index), queryStringParameters = "" })" class="btn btn-primary btn-sm m-l-5 pull-right m-b-5">View</a>
                                                    }
                                                    else if (@item.ChillerType == enChillerType.Compressor.ToString())
                                                    {
                                                        <a href="@Url.Action("EditCompressor", "Compressor",new {ModelID = @item.ModelID, RedirectTo = Convert.ToString(enAction.Index), queryStringParameters = "" })" class="btn btn-primary btn-sm m-l-5 pull-right m-b-5">View</a>
                                                    }

                                                }
                                            </p>
                                            <h5 class="media-heading">@DashboardHelper.GetNewsFeedChillerHeading(@item.StateID, @item.ChillerType)</h5>
                                            <p>@DashboardHelper.GetNameForChillerItem(@item.ChillerType) model <b>@item.ModelNumber</b> has been @DashboardHelper.GetStateActionForDisplayText(@item.StateID) by @item.ActionBy </p>
                                        </div>
                                    </li>
                                //}
                            }


                        </ul>
                    </div>


                </div>


            </div>
            <!-- end panel -->
        </div>
        <!-- end col-8 -->

        <div class="col-md-4">

            <!-- Saved Records START HERE -->
            <div  class="widget widget-stats bg-green">
                
                @Html.Partial("~/Views/Home/_IndexSavedRecords.cshtml")

                
            </div>
            <!-- Saved Records END HERE -->
            <!-- Submited Records START HERE -->
            <div class="widget widget-stats bg-primary">
                @Html.Partial("~/Views/Home/_IndexSubmittedRecords.cshtml")

            </div>
            <!-- Submited Records END HERE -->
            <!-- Rejected Records START HERE -->
            <div class="widget widget-stats bg-danger">
                @Html.Partial("~/Views/Home/_IndexRejectedRecords.cshtml")

            </div>
            <!-- Rejected Records END HERE -->

        </div>


    </div>
    <!-- end row -->
</div>
<script type="text/javascript">
    //setInterval("$('#page-container').load('Home/Index')", 10000);
    //$("#page-loader").removeClass("fade in top bottom left right");
    //$("#page-loader").fadeOut();

    function OpenRequestedModel(ModelID)
{
    var url = '@Url.Action("EditUnitCooler", "UnitCooler")';
    // do something with the url client side variable, for example redirect
    window.location.href = url;

}

</script>


@*<script type='text/javascript'>
        $("#nav").hide();
    </script>*@

Hussmann Prototypes/Hussmann Release/Compressor/Hussmann/Views/Home/_IndexRejectedRecords.cshtml
@using Hussmann.Common.Helper

<div class="height-xs" data-scrollbar="true">
    <div class="stats-icon stats-icon-md"></div>
    <div class="stats-number"><i class="fa fa-ban"></i> Recently Rejected Records</div>
    @foreach (var item in Model.CombinedRejectedRecords)
    {
        <hr class="brack-line">
        <div class="stats-title underline text-white">
            <img src="@DashboardHelper.GetImageForChillerItem(@item.ChillerType)" alt="" class="rounded-corner pull-left save-recored-img" />
            <span class="stats-desc pull-right text-right" style="padding-right:7px;">@item.LastModifiedOn</span>
            <h5>
            @DashboardHelper.GetNameForChillerItem(@item.ChillerType)
            </h5>
            <p>Model <b>@item.ModelNumber</b> rejected by <b>@item.ActionBy</b>.</p>
        </div>
    }
</div>

Hussmann Prototypes/Hussmann Release/Compressor/Hussmann/Views/Home/_IndexSavedRecords.cshtml
@using Hussmann.Common.Helper
@using Hussmann.Common.Enumeration
<div class="height-xs" data-scrollbar="true">
    <div class="stats-icon stats-icon-md"></div>
    <div class="stats-number"><i class="fa fa-check"></i> Recently Saved Records</div>
    @foreach (var item in Model.CombinedSavedRecords)
    {
        <hr class="brack-line">
        <div class="stats-title underline text-white">
            <img src="@DashboardHelper.GetImageForChillerItem(@item.ChillerType)" alt="" class="rounded-corner pull-left save-recored-img" />
            @if (@item.ChillerType == enChillerType.UnitCooler.ToString())
            {
                <span class="stats-desc pull-right text-right"><a href="@Url.Action("EditUnitCooler", "UnitCooler", new { ModelID = @item.ModelID })" class="btn btn-white btn-sm pull-right" style="margin-right: 8px;">View</a></span>
            }
            else if (@item.ChillerType == enChillerType.Condenser.ToString())
            {
                <span class="stats-desc pull-right text-right"><a href="@Url.Action("EditCondenser", "Condenser",new {ModelID = @item.ModelID })" class="btn btn-white btn-sm pull-right" style="margin-right: 8px;">View</a></span>
            }
            else if (@item.ChillerType == enChillerType.Compressor.ToString())
            {
                <span class="stats-desc pull-right text-right"><a href="@Url.Action("EditCompressor", "Compressor", new {ModelID = @item.ModelID })" class="btn btn-white btn-sm pull-right" style="margin-right: 8px;">View</a></span>
            }
            <span class="stats-desc pull-right text-right" style="padding-right:5px;">@item.LastModifiedOn</span>

            <h5>
                @DashboardHelper.GetNameForChillerItem(@item.ChillerType)
            </h5>
            <p>Model <b>@item.ModelNumber</b> saved by <b>@item.CreatedBy</b>  </p>

        </div>
    }
</div>

Hussmann Prototypes/Hussmann Release/Compressor/Hussmann/Views/Home/_IndexSubmittedRecords.cshtml
@using Hussmann.Common.Helper
@using Hussmann.Common.Enumeration
<div class="height-xs" data-scrollbar="true">

    <div class="stats-icon stats-icon-md"></div>
    <div class="stats-number"><i class="fa fa-paper-plane"></i> Recently Submitted Records</div>
    @foreach (var item in Model.CombinedSubmittedRecords)
    {
        <hr class="brack-line">
        <div class="stats-title underline text-white">
            <img src="@DashboardHelper.GetImageForChillerItem(@item.ChillerType)" alt="" class="rounded-corner pull-left save-recored-img" />
            @if (@item.ChillerType == enChillerType.UnitCooler.ToString())
            {
                <span class="stats-desc pull-right text-right"><a href="@Url.Action("EditUnitCooler", "UnitCooler",new {ModelID = @item.ModelID })" class="btn btn-white btn-sm pull-right" style="margin-right: 8px;">View</a></span>
            }
            else if (@item.ChillerType == enChillerType.Condenser.ToString())
            {
                <span class="stats-desc pull-right text-right"><a href="@Url.Action("EditCondenser", "Condenser",new {ModelID = @item.ModelID })" class="btn btn-white btn-sm pull-right" style="margin-right: 8px;">View</a></span>
            }
            else if (@item.ChillerType == enChillerType.Compressor.ToString())
            {
                <span class="stats-desc pull-right text-right"><a href="@Url.Action("EditCompressor", "Compressor", new {ModelID = @item.ModelID })" class="btn btn-white btn-sm pull-right" style="margin-right: 8px;">View</a></span>
            }
            <span class="stats-desc pull-right text-right" style="padding-right:5px;">@item.LastModifiedOn</span>
            <h5>
                @DashboardHelper.GetNameForChillerItem(@item.ChillerType)

            </h5>
            <p>Model <b>@item.ModelNumber</b> submitted by <b>@item.ActionBy</b>  </p>


        </div>
    }
</div>